apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  DB_NAME: {{ .Values.DB_NAME | b64enc | quote }}
  DB_USER: {{ .Values.DB_USER | b64enc | quote }}
  DB_PASSWORD: {{ .Values.DB_PASSWORD | b64enc | quote }}
  DB_ROOT_PASSWORD: {{ .Values.DB_ROOT_PASSWORD | b64enc | quote }}
