apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-mvn.fullname" . }}
  labels:
    {{- include "mysql-mvn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      name: mysql
  selector:
    {{- include "mysql-mvn.selectorLabels" . | nindent 4 }}
